### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by PuRonglong** [trsoliu/vue-audio#2]
![image](https://user-images.githubusercontent.com/8725006/57830820-df5ad980-77e5-11e9-99ef-38eafde71d5c.png)
@trsoliu

**Comment by trsoliu** [comment]
> ![image](https://user-images.githubusercontent.com/8725006/57830820-df5ad980-77e5-11e9-99ef-38eafde71d5c.png)
> @trsoliu

加一下群来找我，群号:535798405

**Comment by trsoliu** [comment]
vue-loader问题
