### ISSUE TITLE
音量bar 拖动直接静音了

### ISSUE THREAD

**Issue by BefightingMan** [trsoliu/vue-audio#8]
我有个素材文件夹，里面有很多音频，第一个音频拖动音量条没问题，后面的拖动直接静音了，我是在v-for里面生成的多个。有没有方法可以解决

**Comment by trsoliu** [comment]
可以解决，你加一下文档里给的群找下我

**Comment by trsoliu** [comment]
> 我有個素材文件夾，裡面有很多音頻，第一個音頻預定音量條沒問題，後面的直接直接靜音了，我是在v-for裡面生成的多個。有沒有方法可以解決

vue-audio-native@0.1.37 我已经修复发布了新版本，重新下载安装即可，感谢反馈问题
